### ISSUE TITLE
Inspiration at Rector

### ISSUE THREAD

**Issue by TomasVotruba** [Enalean/simpletest2mockery#1]
Hey guys, I'm happy that more poeple are lazy like me and start to develop such tool :+1: 

You might like https://github.com/rectorphp/rector as well. 

How does it differ from your approach?

**Comment by vaceletm** [comment]
I took me time but I had a look at your project. It's really great, that nice job.

However, I'm wondering if we could really use it in our context. Let me detail a bit. For simple transformations like explained in introduction and blog post, it would prefectly match the need as it's rather straightforward.
But we also need to do structural changes with context and analysis of the call stack, for basic stuff like properties set in setUp and redefined in test methods but later on more advanced to detect stuff like:
```
$mock->expectCallCount(2);
$mock->expectAt(0, 'stuff', array(1, 2));
$mock->expectAt(1, 'stuff', array(3, 4));
```

to

```
$mock->shouldReceive('stuff')->with(1, 2)->ordered();
$mock->shouldReceive('stuff')->with(3, 4)->ordered();
```
How would Rector help us to do that ?

**Comment by TomasVotruba** [comment]
Hey, 

I see 4 steps to be done:

- find `expectCallCount` call 
- remove it
- find `expectAt()` call
- change it to chain call with other values and put original arguments to propper places

**Comment by vaceletm** [comment]
It's not that simple, we need to match
```
expectCallCount('stuff', X);
expectAt(0, 'stuff', ...)
...
expectAt(X-1, 'stuff', ...)
```
and ideally even
```
expectAt(0, 'stuff', ...)
...
expectAt(X-1, 'stuff', ...)
expectCallCount('stuff', X);
```

**Comment by TomasVotruba** [comment]
That is draft of course, not final Rector code :) 
All edge cases are tested and polished usually in build progres.

**Comment by vaceletm** [comment]
Do you have example of such a code we can look at ?

**Comment by TomasVotruba** [comment]
This one will add one method call and rename other method call:

- https://github.com/rectorphp/rector/blob/master/src/Rector/Contrib/Nette/Application/TemplateRegisterHelperRector.php

**Comment by TomasVotruba** [comment]
If you'd send me before/after simple failing test for the code in your first comment, I could prepare draft for you.

That would be practical and I could expaling what happens where in comment. It's the best way to show Rector to new one.

I needs 3 files:

- correct: https://github.com/rectorphp/rector/pull/338/files#diff-ecaf8c4d364f7e80137654815c7bb398
- wrong: https://github.com/rectorphp/rector/pull/338/files#diff-54c3539dfefafbc29e5ce04cab205565
- and TestCase: https://github.com/rectorphp/rector/pull/338/files#diff-8b2b4ac444ef1b940cd8b9c7ebee0026

I'd place it under `tests/Rector/FrameworkMigration/SimpleTestToMockery`

**Comment by vaceletm** [comment]
Thanks for the links, we will have a look at them to see if we can contribute
